import Head from 'next/head'
import { PostCard, Categories, PostWidget } from '../component';
import { getPosts } from '../services';

// const posts = [
//   {title:'React testing', excerpt: 'Learn react testing'},
//   {title:'React with tailwind', excerpt: 'Learn react with talwind'},
// ]

export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Pablito Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto pb-6 whitespace-nowrap overflow-hidden overflow-ellipsis">
        <span className="font-bold text-xl text-white">↓ Esta es mi ultima publicación ↓ </span>
      </div>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post) => <PostCard post={post.node} key={post.title} />)}
        </div>
        <div className='lg:col-span-4 col-span-1 '>
          <div className='lg:sticky relative top-8 '>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  )
}


export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts }
  }
}